# -*- coding: utf-8 -*-
"""Sales & Revenue Performance Analysis with Power BI, SQL & Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A1olafj7xyB8s8HWvqMDKy4o2Uwu5mge
"""

import numpy as np
import pandas as pd
df=pd.read_csv("/content/Superstore_Sales_Project_Dataset.csv")
df

df.shape

df.info()

df.isna().sum()

df.describe()

df['Category'].value_counts()

df['Segment'].value_counts()

df['Region'].value_counts()

Total_sales=float(df['Sales'].sum())
print("Total_sales:",Total_sales)

Total_profit=df['Profit'].sum()
print("Total profit:",Total_profit)

Average_discount=df['Discount'].mean()
print("Average discount:",Average_discount)

# Group by Category
category_summary = df.groupby('Category')[['Sales', 'Profit']].sum().reset_index()
category_summary

import seaborn as sns
import matplotlib.pyplot as plt
# Sales by Category
sns.barplot(data=category_summary, x='Category', y='Sales')
plt.title("Total Sales by Category")
plt.show()

# Profit by Category
sns.barplot(data=category_summary, x='Category', y='Profit')
plt.title("Total Profit by Category")
plt.show()

# Group by Segment
segment_summary = df.groupby('Segment')[['Sales', 'Profit']].sum().reset_index()
segment_summary

sns.barplot(data=segment_summary, x='Segment', y='Sales')
plt.title("Sales by Segment")
plt.show()

sns.barplot(data=segment_summary, x='Segment', y='Profit')
plt.title("Profit by Segment")
plt.show()

# Group by Region
region_summary = df.groupby('Region')[['Sales', 'Profit']].sum().reset_index()
region_summary

sns.barplot(data=region_summary, x='Region', y='Sales')
plt.title("Sales by Region")
plt.show()

sns.barplot(data=region_summary, x='Region', y='Profit')
plt.title("Profit by Region")
plt.show()

subcat_summary = df.groupby('Sub-Category')[['Profit']].sum().sort_values('Profit', ascending=False).reset_index()
subcat_summary

sns.barplot(data=subcat_summary, x='Profit', y='Sub-Category')
plt.title("Top Sub-Categories by Profit")
plt.xlabel("Profit")
plt.ylabel("Sub-Category")
plt.show()

#Q1: Which Category contributes most to Sales?
df.groupby('Category')['Sales'].sum().sort_values(ascending=False).head(1)

#Q2: Which Category is most profitable?
df.groupby('Category')['Profit'].sum().sort_values(ascending=False).head(1)

#Q3: Which Sub-Category generates highest profit?
df.groupby('Sub-Category')['Profit'].sum().sort_values(ascending=False).head(1)

#Q4: Are there any loss-making Sub-Categories?
df.groupby('Sub-Category')['Profit'].sum().sort_values().head(5)

#Q5: Which Region has highest sales?
df.groupby('Region')['Sales'].sum().sort_values(ascending=False).head(1)

#Q6: Which Region is most profitable?
df.groupby('Region')['Profit'].sum().sort_values(ascending=False).head(1)

#Q7: Which Segment contributes most to total sales?
df.groupby('Segment')['Sales'].sum().sort_values(ascending=False).head(1)

#Q8: Which Segment is most profitable?
df.groupby('Segment')['Profit'].sum().sort_values(ascending=False).head(1)

#Q9: Which Segment needs attention (low profit / high discount)?
df.groupby('Segment')[['Profit','Discount']].mean().sort_values('Profit')

#Q10: How does Discount affect Profit?
df.groupby('Discount')['Profit'].mean().sort_values()

#Q11: Are high discounts causing losses in any Category or Sub-Category?
df[df['Discount']>=0.2].groupby(['Category','Sub-Category'])['Profit'].sum().sort_values()

#Q12: Which Month has highest Sales?

df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')
df['Month_Num'] = df['Order_Date'].dt.month
df['Month'] = df['Order_Date'].dt.month_name().str[:3]

df.groupby(['Month_Num','Month'])['Sales'].sum().sort_values(ascending=False).head(1)

#Q13: Which Month has highest Profit?
df.groupby('Month')['Profit'].sum().reindex(['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']).sort_values(ascending=False).head(1)

#Q14: Are there seasonal trends for Categories or Segments?
df.groupby(['Month','Category'])['Sales'].sum().unstack().plot(figsize=(10,5))